### PR TITLE
[serverinfo] Add in level 4 (phone verification)

### PR DESCRIPTION
**Pull request by xshotD**
Feel free to suggest another name if 'Extreme' isn't your thing.

### CODE REVIEW

**Comment by Rayzr522** [comment]
Looks good!

**Comment by Rayzr522** [comment]
@xshotD if you're part of my Discord server, please post your username here so I can give you the Contributor role.

**Comment by xshotD** [comment]
Not in it, but will join.

**Comment by xshotD** [comment]
Discord.io wasn't working for me a bit, so I had to delay my join for a few hours at least.

But now I'm there. lold#6978

**Comment by Rayzr522** [comment]
Role added.

**Pull request merged**
