### PR TITLE
Adds current command to check the current weather

### PR DESCRIPTION
**Pull request by NITEHAWKDevs**
Example Usage: //current <-f or -c> <location>

### CODE REVIEW

**Comment by JMccormick264** [comment]
Love it. its working great for me!

**Comment by Rayzr522** [comment]
Pending the return of @NITEHAWKDevs to this PR, I'm closing it. Feel free to reopen when you've rewritten to account for all the changes that've been made.

On a side note, the new `bot.storage` system should help with this. We should create a `settings` file for command settings like this.

**Comment by yonilerner** [comment]
@Rayzr522 We have a way for commands to specify extra config options that hook into the standard config system. You just export a `configs` array, where each item is an object to be used as a "question" for the config `prompt`

**Comment by Rayzr522** [comment]
@yonilerner we don't want this to be in the setup prompt. We want to prompt people for a default unit (°F or °C) only when they use this command. The setup prompt is only intended to set up the bare essentials. We should probably even consider making a management command for the assistant bot system, as not everyone will want to use that.

**Pull request closed without merging**
