### PR TITLE
Added shorturl

### PR DESCRIPTION
**Pull request by bobmcdouble3**
Added shorturl. Shorten URLs in chat with "//short <url>"

### CODE REVIEW

**Comment by Rayzr522** [comment]
I can take the core of this PR and implement it myself, but the PR itself has too many problems. I can't accept it without asking you to make so many changes that I would basically be re-writing it myself anyways. I'll still give you credit, though, since the original PR is yours.

**Comment by Rayzr522** [comment]
Added in #d645784. Thanks for the PR!

**Comment by bobmcdouble3** [comment]
Your welcome. Sorry I wasn't sure of your standards

**Comment by Rayzr522** [comment]
Yeah, I understand, and we have almost no documentation for contributors, so it's understandable. I simply don't have the time to handle all that right now and set up a proper contributors document, as well as show you how to fix the command. This was the fastest and easiest way to handle this, sorry for kinda slashing your PR.

**Pull request closed without merging**
