### PR TITLE
Es6 pointy functions

### PR DESCRIPTION
**Pull request by l-lindwall**
Remove all instances of function and replace them with es6 pointy arrow functions.

### CODE REVIEW

**Comment by Rayzr522** [comment]
I mean, I suppose we could merge this, but why? What's wrong with having mixed functions/lambdas?

> Side note: they're not "pointy arrow functions". They're lambdas.

**Comment by ldwall** [comment]
Nothing wrong with them, just for consistency.

Den 24 nov. 2017 19:13 skrev "Rayzr" <notifications@github.com>:

**Comment by Rayzr522** [comment]
I suppose I'm fine with this. However, before I accept, I would prefer if all the single-variable lambdas had the parenthesis removed.

**Comment by Rayzr522** [comment]
Appears to be abandoned. I might as well just close this.

**Pull request closed without merging**
