### PR TITLE
Added statement about YT video produced by IkBrian.

### PR DESCRIPTION
**Pull request by Orotusso**

### CODE REVIEW

**Comment by Rayzr522** [comment]
I get it, we're all frustrated by the problems that IkBrian's video causes us, but isn't this just *asking* for trouble?

**Comment by Orotusso** [comment]
With their refusal to fix the issues, and with support mostly falling on the RayzrDev server, it's a needed addition to explain the situation with the video.

**Comment by abyssvi** [comment]
Don't think this is necessary. People coming from that video aren't going to read this - and this isn't doing anything but giving him free publicity.

**Comment by Orotusso** [comment]
Pull request closed. Result: Not a necessary addition

**Pull request closed without merging**
